# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'News' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for News
  pod 'Alamofire' # 网络请求
  pod 'HandyJSON' # json处理
  pod 'SwiftyJSON' # 解析json
  pod 'Kingfisher' # 加载图片
  pod 'IBAnimatable' # 让layer时时显示在xib上
  pod 'SwiftTheme' # 更改主题
  pod 'RxSwift' # rac
  pod 'RxCocoa'
  pod 'SQLite.swift' # SQLite数据库
  pod 'SVProgressHUD' # 弹框
  pod 'MJRefresh' # 刷新
  pod 'SGPagingView'
  pod 'SGPageView'
  pod 'BMPlayer', :git => 'https://github.com/ceeyang/BMPlayer.git'
  
end
